---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio-server-{{ ORGANIZATION_NAME }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - name: server
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: console
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: minio-server-{{ ORGANIZATION_NAME }}
  type: ClusterIP
