################################################################################
# Copyright (c) 2017-2021 UCit SAS
# All Rights Reserved
#
# This software is the confidential and proprietary information
# of UCit SAS ("Confidential Information").
# You shall not disclose such Confidential Information
# and shall use it only in accordance with the terms of
# the license agreement you entered into with UCit.
################################################################################

# This script allows Master and Compute to join an active directory domain

- hosts: localhost
  vars:
    HEROES_DEPLOYMENT_DIR: "/opt/heroes/platform/sbin"
    FASTAPI_VERSION: "0.3"

  tasks:

    - name: Install python3 as prerequisites to install PostGreSQL
      yum:
        name:
          - postgresql-server
          - expect
        state: present


    - name: Create postgresql group
      group:
        name: postgresql
        local: yes
        state: present


    - name: Create postgresql user
      user:
        name: postgresql
        local: yes
        group: postgresql
        create_home: yes
        home: /var/lib/pgsql
        system: yes


    - name: Create /var/run/postgresql dir with postgresql user as owner
      ansible.builtin.file:
        path: /var/run/postgresql
        state: directory
        owner: postgresql
        group: postgresql
